version: "3"
services:

  postgres:
    image: 'postgres'
    container_name: postgres
    environment:
      - 'POSTGRES_DB=CadastreCompany'
      - 'POSTGRES_USER=cadastre'
      - 'POSTGRES_PASSWORD=2003'
    networks:
      - host_env
    volumes:
      - database:/var/lib/postgresql/data




  rabbitmq:
    image: 'rabbitmq'
    container_name: rabbitmq
    environment:
      - 'RABBITMQ_DEFAULT_USER=alex'
      - 'RABBITMQ_DEFAULT_PASS=alex'
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - host_env
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  site:
    image: 'spaxer/cadastre-site'
    container_name: site
    environment:
      - VIRTUAL_HOST=cadastre-mordovia.ru #TODO
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_HOST=cadastre-mordovia.ru
    ports:
      - "8080:8080"
    expose:
      - 8080
    networks:
      - host_env
    depends_on:
      - rabbitmq

  dbpostgres:
    image: 'spaxer/cadastre-dbpostgres'
    container_name: dbpostgres
    ports:
      - "8088:8088"
    expose:
      - 8088
    networks:
      - host_env
    depends_on:
      - postgres
      - rabbitmq
      - site

volumes:
  database:
  rabbitmq_data:

networks:
  host_env: