drop table if exists Engineer;
drop table if exists Client;
 

create table Engineer (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(12) NOT NULL,
    login varchar(50) NOT NULL unique,
    password varchar NOT NULL,
    tg_id int unique
);

comment on table Engineer is 'Предназначена для хранения данных пользователей (инженеров).';

create table Client (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(40) NOT NULL,
    phone varchar(11) NOT NULL,
    created_data TIMESTAMP NOT null,
    eng_id int references Engineer(id) on delete set null
);

comment on table Client is 'Предназначена для хранения данных о новых клиентах (обращениях).';

create table PriceList (
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mezhevaniye varchar NOT NULL,
    tech_plan varchar NOT NULL,
    akt_inspection varchar NOT NULL,
    scheme_location varchar NOT NULL,
    takeaway_borders varchar NOT NULL,
    lastChange TIMESTAMP NOT null
);

comment on table PriceList is 'Предназначена для хранения данных о кратком прайс листе на странице.';
